name: ${APP_NAME}

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_INTERNAL_PORT}
      NGINX_INTERNAL_PORT: ${NGINX_INTERNAL_PORT}
    volumes:
      - ./public:/var/www/public
    depends_on:
      - app

  app:
    hostname: ${APP_HOST}
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: app-dev
    volumes:
      - ./:/app
    expose:
      - ${APP_INTERNAL_PORT}
    environment:
      APP_PORT: ${APP_INTERNAL_PORT}
    healthcheck:
      test: [ "CMD", "php", "-v" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  app-consumer:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: app-consumer
    volumes:
      - ./:/app
    healthcheck:
      test: [ "CMD", "php", "-v" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      app:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    hostname: ${DB_HOST}
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ:-Asia/Vladivostok}
    command: -p ${DB_INTERNAL_PORT}
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile
      target: rabbitmq
    container_name: ${RABBITMQ_HOST}
    ports:
      - ${RABBITMQ_EXTERNAL_PORT}:${RABBITMQ_INTERNAL_PORT}
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_JOBS_QUEUE: ${RABBITMQ_JOBS_QUEUE}
      RABBITMQ_INTERNAL_PORT: ${RABBITMQ_INTERNAL_PORT}
      TZ: ${TZ:-Asia/Vladivostok}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
  rabbitmq-data:
