name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PHP_VERSION: 8.4

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile', '**/docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Create .env file
        run: make env

      - name: Build Docker containers
        run: |
          make build || (docker-compose logs app && exit 1)

      - name: Initialize application
        run: make init

      - name: Run composer validate
        run: make composer-validate

      - name: Run PHPStan
        run: make lint

      - name: Run PHP-CS-Fixer
        run: make fix-check

      - name: Run Rector
        run: make rector-check

      - name: Run Deptrac
        run: make deptrac

      - name: Run tests
        run: make run-tests

      - name: Clean up
        if: always()
        run: make clean
